NAME = "hazel / shell"

GUILD_ID = 1429674770596761685
NEO_POLITA = 1395939916189405325

SHELL_ACCESS_ROLE = "> connected..."
ACHIEVEMENTS_CHANNEL = 1429897092226351244

VERSION = "2.5.1"

USERMOD_MAPPINGS = {
    "pronouns": {
        "he": "he / him",
        "him": "he / him",
        "he/him": "he / him",
        "masc": "he / him",
        "masculine": "he / him",
        "she": "she / her",
        "her": "she / her",
        "she/her": "she / her",
        "fem": "she / her",
        "feminine": "she / her",
        "they": "they / them",
        "them": "they / them",
        "they/them": "they / them",
        "it": "it / its",
        "its": "it / its",
        "it/its": "it / its",
        "other": "/ other",
        "ask": "ask / me",
        "askme": "ask / me",
        "any": "/ any",
    },
    "proficiency": {
        "new": "\\ new to computer science",
        "newcs": "\\ new to computer science",
        "beginner": "\\ new to computer science",
        "computerscience": "\\ new to computer science",
        "newlinux": "\\ new to linux",
        "linux": "\\ new to linux",
        "linuxnew": "\\ new to linux",
    },
    "os": {
        "windows": "\\ windows",
        "win": "\\ windows",
        "windowsxp": "\\ windows xp",
        "xp": "\\ windows xp",
        "windows7": "\\ windows 7",
        "win7": "\\ windows 7",
        "windowsnt": "\\ windows (pre-nt)",
        "prent": "\\ windows (pre-nt)",
        "oldwindows": "\\ windows (pre-nt)",
        "win95": "\\ windows (pre-nt)",
        "win98": "\\ windows (pre-nt)",
        "macos": "\\ macos",
        "mac": "\\ macos",
        "osx": "\\ macos",
        "darwin": "\\ macos",
        "bsd": "\\ berkeley software distribution",
        "freebsd": "\\ berkeley software distribution",
        "openbsd": "\\ berkeley software distribution",
        "netbsd": "\\ berkeley software distribution",
        "berkeley": "\\ berkeley software distribution",
        "arch": "\\ arch linux",
        "archlinux": "\\ arch linux",
        "btw": "\\ arch linux",
        "ubuntu": "\\ ubuntu",
        "gentoo": "\\ gentoo",
        "fedora": "\\ fedora",
        "rhel": "\\ fedora",
        "nixos": "\\ nixos",
        "nix": "\\ nixos",
        "debian": "\\ debian",
        "deb": "\\ debian",
        "void": "\\ void",
        "voidlinux": "\\ void",
        "redhat": "\\ red hat",
        "popos": "\\ pop! os",
        "pop": "\\ pop! os",
        "haiku": "\\ haiku",
        "solaris": "\\ solaris",
        "centos": "\\ centos",
        "bedrock": "\\ bedrock",
        "alpine": "\\ alpine",
        "steamos": "\\ steamos",
        "steam": "\\ steamos",
        "fromscratch": "\\ from scratch",
        "lfs": "\\ from scratch",
        "slackware": "\\ slackware",
        "slack": "\\ slackware",
        "chromeos": "\\ chromeos",
        "chrome": "\\ chromeos",
        "aix": "\\ aix",
        "plan9": "\\ plan9",
    },
    "ping": {
        "technews": "+ tech news",
        "news": "+ tech news",
        "support": "+ ping for support",
        "help": "+ ping for support",
        "announcements": "+ announcements",
        "announce": "+ announcements",
    },
    "channel": {
        "controversial": "+ controversial",
        "politics": "+ controversial",
    },
}

USERMOD_CATEGORIES = {
    "pronouns": "pronouns",
    "proficiency": "proficiency level",
    "os": "operating system",
    "ping": "ping preferences",
    "channel": "extra channel access",
}

ACHIEVEMENTS = {
    "haveacookie": {
        "name": "have a cookie",
        "description": "say thank you or give a cookie to someone",
        "rarity": "common",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "haveacookietray": {
        "name": "have a cookie tray",
        "description": "say thank you or give cookies 20 times",
        "rarity": "rare",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "haveacookiemachine": {
        "name": "have a cookie machine",
        "description": "say thank you or give cookies 100 times",
        "rarity": "rare",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "yay": {
        "name": "yay :3",
        "description": "get your first cookie",
        "rarity": "common",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "cookietray": {
        "name": "cookie tray",
        "description": "receive 20 cookies total",
        "rarity": "rare",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "cookiemachine": {
        "name": "cookie machine",
        "description": "receive 100 cookies total",
        "rarity": "rare",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "bakery": {
        "name": "bakery",
        "description": "get 1 cake",
        "rarity": "legendary",
        "trigger_type": "manual",
        "trigger_value": None,
        "role": None,
    },
    "echo": {
        "name": "hello world (hello world)",
        "description": "run the echo command",
        "rarity": "common",
        "trigger_type": "command",
        "trigger_value": "echo",
        "role": None,
    },
    "imtrapped": {
        "name": "i don't know how to exit...",
        "description": "run the wrong exit command",
        "rarity": "common",
        "trigger_type": "command",
        "trigger_value": "exit",
        "role": None,
    },
    "crash": {
        "name": "crash!",
        "description": "run an existing command that gives a non-zero exit code.",
        "rarity": "rare",
        "trigger_type": "nonzero_exit",
        "trigger_value": None,
        "role": "> bot breaker",
    },
    "neopolita": {
        "name": "neo / polita",
        "description": "be a member of both hazel / run and neo * polita",
        "rarity": "rare",
        "trigger_type": "mutual_servers",
        "trigger_value": None,
        "role": "> neo / polita",
    },
    "ricer": {
        "name": "ricer instinct",
        "description": "run hazelfetch",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": (">hazelfetch", 1),
        "role": "> ricer instinct",
    },
    "packaged": {
        "name": "packaged",
        "description": "run the pacman package manager",
        "rarity": "common",
        "trigger_type": "command",
        "trigger_value": "pacman",
        "role": "> packaged",
    },
    "meow": {
        "name": "meow :3",
        "description": "send 20 messages containing the word meow",
        "rarity": "common",
        "trigger_type": "message_count",
        "trigger_value": ("meow", 20),
        "role": "> meow :3",
    },
    "meowmeow": {
        "name": "meow meow :3 :3",
        "description": "send 100 messages containing the word meow. i like cats too :3",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": ("meow", 100),
        "role": None,
    },
    "supermeow": {
        "name": "super meow... :3 :3 :3",
        "description": "send 500 messages containing the word meow. a true cat enthusiast.",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": ("meow", 500),
        "role": None,
    },
    "literallyobsessive": {
        "name": "literally obsessive...",
        "description": "send 1,000 messages containing the word meow. this user really loves cats.",
        "rarity": "legendary",
        "trigger_type": "message_count",
        "trigger_value": ("meow", 1000),
        "role": None,
    },
    "theendofallmeows": {
        "name": "the end of all meows... :3",
        "description": "send 100,000 messages containing the word meow. this user is probably a cat.",
        "rarity": "master",
        "trigger_type": "message_count",
        "trigger_value": ("meow", 100000),
        "role": None,
    },
    "whatdidyousay": {
        "name": "wuf :3",
        "description": "send 20 messages containing the word woof",
        "rarity": "common",
        "trigger_type": "message_count",
        "trigger_value": ("woof", 20),
        "role": "> woof :3",
    },
    "saythatagain": {
        "name": "say that again...",
        "description": "send 100 messages containing the word woof",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": ("woof", 100),
        "role": "> got that dawg",
    },
    "suchadog": {
        "name": "such a dog...",
        "description": "send 500 messages containing the word woof",
        "rarity": "legendary",
        "trigger_type": "message_count",
        "trigger_value": ("woof", 500),
        "role": None,
    },
    "needygirl": {
        "name": "internet overdose",
        "description": "play NEEDY GIRL OVERDOSE",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["NEEDY GIRL OVERDOSE", "NEEDY STREAMER OVERLOAD"],
        "role": None,
    },
    "bilingual": {
        "name": "bilingual :3",
        "description": "send 10 messages containing both meow and woof",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": (("meow", "woof"), 10),
        "role": None,
    },
    "yourewhat": {
        "name": "you're what?",
        "description": 'say "i\'m confused" five times',
        "rarity": "common",
        "trigger_type": "message_count",
        "trigger_value": ("i'm confused", 5),
        "role": "> a_confuseduser",
    },
    "toroplushie": {
        "name": ":toroplushie:",
        "description": "use the :toroplushie: emote 20 times",
        "rarity": "rare",
        "trigger_type": "message_count",
        "trigger_value": (":toroplushie:", 20),
        "role": "> XD",
    },
    "thestart": {
        "name": "the start",
        "description": "run a hzsh session for the first time",
        "rarity": "common",
        "trigger_type": "first_hzsh",
        "trigger_value": None,
        "role": "> the start",
    },
    "gaming": {
        "name": "we should play sometime...",
        "description": "play R.E.P.O., Minecraft, or THE FINALS",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["R.E.P.O.", "Minecraft", "THE FINALS"],
        "role": "> we should play sometime...",
    },
    "elitegamer": {
        "name": "elite gamer",
        "description": "have 100+ games on a linked public Steam profile",
        "rarity": "legendary",
        "trigger_type": "steam_games",
        "trigger_value": 100,
        "role": "> elite gamer",
    },
    "blocky": {
        "name": "blocky",
        "description": "run minecraft, prismlauncher, or multimc in hzsh",
        "rarity": "common",
        "trigger_type": "command",
        "trigger_value": ["minecraft", "prismlauncher", "multimc"],
        "role": "> blocky",
    },
    "accessdenied": {
        "name": "access denied",
        "description": "try running sudo, su, or doas",
        "rarity": "common",
        "trigger_type": "command",
        "trigger_value": ["sudo", "su", "doas"],
        "role": None,
    },
    "rulebreaker": {
        "name": "rule breaker",
        "description": "be muted or warned",
        "rarity": "common",
        "trigger_type": "infraction",
        "trigger_value": ["mute", "warn"],
        "role": None,
    },
    "gambling": {
        "name": "let's go gambling!!!!",
        "description": "play Balatro, CloverPit or Buckshot Roulette",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["Balatro", "CloverPit", "Buckshot Roulette"],
        "role": None,
    },
    "honkaistarrail": {
        "name": "why do we dream..",
        "description": "play Honkai: Star Rail",
        "rarity": "common",
        "trigger_type": "presence",
        "trigger_value": ["Honkai: Star Rail"],
        "role": None,
    },
    "inscryption": {
        "name": "what is the karnoffel code?",
        "description": "play Inscryption",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["Inscryption"],
        "role": None,
    },
    "halflife": {
        "name": "half-life 3 soon",
        "description": "play Half-Life or Half-Life 2",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["Half-Life", "Half-Life 2"],
        "role": None,
    },
    "roblox": {
        "name": "this achievement gives 100 robux",
        "description": "play Roblox",
        "rarity": "common",
        "trigger_type": "presence",
        "trigger_value": ["Roblox"],
        "role": None,
    },
    "ultrakill": {
        "name": "im ultrakilling it",
        "description": "play ULTRAKILL",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": ["ULTRAKILL"],
        "role": None,
    },
    "danganronpa": {
        "name": "the sixteenth student",
        "description": "play Danganronpa: Trigger Happy Havoc, Danganronpa 2: Goodbye Despair, or Danganronpa V3: Killing Harmony",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": [
            "Danganronpa: Trigger Happy Havoc",
            "Danganronpa 2: Goodbye Despair",
            "Danganronpa V3: Killing Harmony",
        ],
        "role": None,
    },
    "ddlc": {
        "name": "just monika",
        "description": "play Doki Doki Literature Club! or Doki Doki Literature Club! Plus",
        "rarity": "common",
        "trigger_type": "presence",
        "trigger_value": [
            "Doki Doki Literature Club!",
            "Doki Doki Literature Club! Plus",
        ],
        "role": None,
    },
    "nekopara": {
        "name": "catgirl's paradise",
        "description": "play any NEKOPARA game",
        "rarity": "rare",
        "trigger_type": "presence",
        "trigger_value": [
            "NEKOPARA Vol. 1",
            "NEKOPARA Vol. 2",
            "NEKOPARA Vol. 3",
            "NEKOPARA Vol. 4",
            "NEKOPARA After",
            "NEKOPARA Extra",
        ],
        "role": None,
    },
    "contributor": {
        "name": "contribute to oss",
        "description": "make a post in #projects",
        "rarity": "common",
        "trigger_type": "forum_post",
        "trigger_value": 1429678941031108741,
        "role": "> contributor",
    },
    "ricingenthusiast": {
        "name": "check out my wallpaper",
        "description": "make a post in #ricing",
        "rarity": "common",
        "trigger_type": "forum_post",
        "trigger_value": 1429680296156073995,
        "role": None,
    },
    "hazelrunner": {
        "name": "hazel / runner",
        "description": "get 20 achievements",
        "rarity": "rare",
        "trigger_type": "achievement_count",
        "trigger_value": 20,
        "role": "",
    },
    "rtfm": {
        "name": "rtfm",
        "description": "read the help page 3 times",
        "rarity": "common",
        "trigger_type": "message_count",
        "trigger_value": (">help", 3),
        "role": None,
    },
    "comeback": {
        "name": "comeback",
        "description": "do not send a message for a week, then send one",
        "rarity": "rare",
        "trigger_type": "inactivity",
        "trigger_value": 604800,
        "role": None,
    },
    "reactionary": {
        "name": "reactionary",
        "description": "react to 20 messages",
        "rarity": "common",
        "trigger_type": "reaction_count",
        "trigger_value": 20,
        "role": None,
    },
    "livereaction": {
        "name": "live (user) reaction",
        "description": "react to 50 messages",
        "rarity": "rare",
        "trigger_type": "reaction_count",
        "trigger_value": 50,
        "role": None,
    },
    "tororeaction": {
        "name": ":toroplushie: REACTION - DID HE REALLY SAY XD?",
        "description": "react with :toroplushie:",
        "rarity": "common",
        "trigger_type": "specific_reaction",
        "trigger_value": "toroplushie",
        "role": None,
    },
}

RARITY_XP = {
    "common": 1,
    "rare": 10,
    "legendary": 20,
    "master": 100,
}

ACHIEVEMENT_MILESTONES = {
    5: "$ navigating... [5]",
    10: "$ mastering... [10]",
    50: "$ réseau noisette [50]",
}
